export {
  completeTask,
  getCurrentLearningActivity,
  getCurrentWeek,
  getCurriculum,
  getMyWeekProgress,
  listWeeklyTasks,
  markTaskDone,
  markTaskIncomplete,
  skipTask,
  startStudy,
  updateMyWeekProgress,
} from './api/curriculumApi'
export type {
  CurrentLearningActivity,
  CurrentLearningActivityTask,
  CurrentLearningActivityTaskCompletion,
  Curriculum,
  CurriculumStatus,
  CurriculumWeek,
  CurriculumWeekStatus,
  CurriculumWeekSummary,
  DoneTaskRequest,
  IncompleteTaskRequest,
  MemberWeekProgress,
  MemberWeekProgressStatus,
  TaskCompletionRequest,
  TaskCompletionResponse,
  TaskCompletionStatus,
  TaskCompletionSummary,
  UpdateWeekProgressRequest,
  WeeklyTask,
  WeeklyTaskType,
} from './model/types'
